### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by iMichaela** [FATHOM5/oscal#2]
As OSCAL user, I am interested in learning more about the OSCAL representation of the SP 800-171. The **Purpose** section of the description reads: "_This repo provides **custom OSCAL content** and supporting tools that enable compliance automation_". This is confusing since I do not know how to interpret what was "customized" - was OSCAL customized, so it is no longer OSCAL 1.0.0? The catalog in OSCAL lists OSCAL version 1.0.0, and no name space was used other than the OSCAL one, so understanding what was customized would be useful.

**Comment by matt-f5** [comment]
@iMichaela Thanks for your comment! By "custom OSCAL content" we mean we've custom developed content _in_ OSCAL, not that we've customized OSCAL itself. I can update the description if it would add clarity
